baseurl = "https://eloicoquoz.github.io/labveilletech"
metaDataFormat = "yaml"
title = "LabVeilleTech - Eloi"
theme = "blist"

DefaultContentLanguage = "fr"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "Hey! I'm Katheryn Fox"
      introSubtitle = "26 y/o junior developer who enjoys social card games, blogging and painting"
      introPhoto = "/labveilletech/picture.jpg"
      logo = "/labveilletech/logo.png"
    [[languages.en.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.en.menu.main]]
        name = "About"
        url = "page/about/"
        weight = 2

    [[languages.en.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3

    [[languages.en.menu.main]]
        name = "Top Post"
        url = "/en/blog/emoji-support/"
        weight = 4

  [languages.de]
    contentDir = "content/de" # Deutsch
    weight = 2
    languageName = "Deutsch"
    title = "Blist (mehrsprachig)"
    description = "Modernes Blog-Theme für Ihre Hugo-Site."
    [languages.de.params]
      introTitle = "Hallo, ich bin Katheryn Fox"
      introSubtitle = "26-jährige Junior-Entwicklerin, die Spaß an sozialen Kartenspielen, Bloggen und Malen hat"
      introPhoto = "/picture.jpg"
      logo = "/labveilletech/logo.png"
    [[languages.de.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.de.menu.main]]
        name = "Über mich"
        url = "page/about/"
        weight = 2

    [[languages.de.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3
        
  [languages.fr]
    contentDir = "content/fr" #French
    weight = 1
    languageName = "Français"
    [languages.fr.params]
      introTitle = "Salut ! Je suis Eloi Coquoz"
      introSubtitle = "Ingénieur des médias de formation, je suis passionné par le sport et la technologie. J'ai voulu commencer une formation dans le domaine du sport mais je me suis blessé et j'ai du changer de voie. Mon but est de pouvoir lier ces deux domaines dans mon métier."
      introPhoto = "/labveilletech/picture.jpg"
      logo = "/labveilletech/logo.png"
    [[languages.fr.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.fr.menu.main]]
        name = "À propos"
        url = "page/about/"
        weight = 2

    [[languages.fr.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Copyright © 2022 - Eloi Coquoz · All rights reserved"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = false

[params.homepage.social]
  # Global params common for both languages
  title = "Follow me"
  description = "I work on everything coding and tweet developer memes"
  linkedin = "https://www.linkedin.com/in/eloi-coquoz/"
  github = "https://github.com/eloicoquoz"
  instagram = "https://instagram.com/coquoz_eloi"

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
